### ISSUE TITLE
Remix on Glitch doesnt work

### ISSUE THREAD

**Issue by MichalRemis** [stimulusjs/stimulus-starter#5]
Hello, I am new to Stimulus, trying it out, but when i click _Remix on Glitch_ button, to run this repo on Glitch it doesn't work. Some other project (without Stimulus) is loaded.

**Comment by javan** [comment]
Thanks for the report! Looks like this is an issue on Glitch's end: https://support.glitch.com/t/clone-from-git-repo-doesnt-work/17442. I left an additional comment there.

In the meantime, you could try running this app locally. Instructions from the README:
> Or, if you'd prefer to work from the comfort of your own text editor, you'll need to clone and set up `stimulus-starter`:
> ```
> $ git clone https://github.com/stimulusjs/stimulus-starter.git
> $ cd stimulus-starter
> $ yarn install
> $ yarn start
> ```

**Comment by javan** [comment]
Should be fixed now: https://support.glitch.com/t/clone-from-git-repo-doesnt-work/17442/5
