### ISSUE TITLE
Glitch not working & local failing too - error with multimap version?

### ISSUE THREAD

**Issue by tonydehnke** [stimulusjs/stimulus-starter#8]
Trying out the Handbook Stimulus-Starter - Hello, Stimulus section and Glitch link fails to load the remix example.  I then tried to do it locally and the `yarn install` fails.  It looks like it is looking for an invalid multimap version: 1.1.1 

The multimap yarnpkg shows 1.1.0 as the latest.

I will see if I can fix it, but wanted to log it here in case I can not.

[yarn-error.log](https://github.com/stimulusjs/stimulus-starter/files/4945345/yarn-error.log)

**Comment by tonydehnke** [comment]
Running `brew update` resolved this for me.. I'll leave this open as the Glitch is still not working.  

Also if anyone knows why it didn't work for me before doing the `brew update`, would love to learn why - as it seemed

**Comment by javan** [comment]
Glitch installs should be working now. Here's one I just made: https://chiseled-immense-airbus.glitch.me. Mind trying again?

**Comment by tonydehnke** [comment]
Glitch works for me now too. :)
